using System;
using System.IO;
using EndlessSky.Sim;
using Godot;

namespace EndlessSky.Game
{
    /// <summary>
    /// Loads the game dataset once per process: $ENDLESS_SKY_DATA, the shipped
    /// universe/, the upstream reference clone, then a sibling es-upstream clone.
    /// Exported builds resolve these paths beside the executable.
    /// </summary>
    public static class EsData
    {
        private static GameData? _data;
        private static string? _dataPath;
        private static bool _searched;

        public static string? DataPath
        {
            get
            {
                if (_searched)
                {
                    return _dataPath;
                }

                _searched = true;
                // Fully qualified: Godot.Environment (the rendering environment) is in
                // scope here and collides with System.Environment.
                string? fromEnv = System.Environment.GetEnvironmentVariable("ENDLESS_SKY_DATA");
                string projectRoot = ProjectSettings.GlobalizePath("res://");
                // Explicit override, shipped content, then reference checkouts.
                string?[] candidates =
                {
                    fromEnv,
                    // The Reach: this project's own universe, generated by
                    // tools/worldgen. Preferred over the upstream reference clone,
                    // which stays on disk because the simulation's parity tests read
                    // it — the game plays our content, the tests check theirs.
                    Path.Combine(projectRoot, "universe"),
                    Path.Combine(projectRoot, "external", "endless-sky", "data"),
                    Path.Combine(projectRoot, "..", "es-upstream", "data"),
                };
                foreach (string? candidate in candidates)
                {
                    if (!string.IsNullOrEmpty(candidate) && Directory.Exists(candidate))
                    {
                        _dataPath = Path.GetFullPath(candidate);
                        break;
                    }
                }

                return _dataPath;
            }
        }

        /// <summary>The loaded universe, or null when no dataset is available.</summary>
        public static GameData? Universe
        {
            get
            {
                if (_data != null)
                {
                    return _data;
                }

                string? path = DataPath;
                if (path == null)
                {
                    return null;
                }

                var data = new GameData();
                data.LoadDirectory(path);
                GD.Print($"[data] loaded {data.Ships.Count} ships, {data.Outfits.Count} outfits, " +
                         $"{data.Systems.Count} systems from {path}");
                if (data.Diagnostics.Count > 0)
                {
                    GD.Print($"[data] {data.Diagnostics.Count} loader diagnostics (first: {data.Diagnostics[0]})");
                }

                _data = data;
                return _data;
            }
        }
    }
}
