"""Renders the generated universe as Endless Sky data files.

The format is the engine's own, not a private one, so everything here is loaded
by the same parser that reads upstream content and is subject to the same rules.
That is the point: content the game already knows how to read needs no special
path through the loader, and anything wrong with it shows up as a parse
diagnostic rather than as a silent shrug.

Two format details are easy to get wrong and expensive to debug:

  * Multi-word keys must be QUOTED — "attitude toward", "visit planet",
    "jump range". Written bare they tokenise as two tokens and never match, and
    nothing complains; the government simply ends up with no enemies.
  * Values containing spaces or quotes must be quoted, and a value containing a
    double quote has to be wrapped in backticks, because the format has no
    escape character.
"""

import os
import zlib
from typing import Dict, List

from galaxy import STAR_SPRITES, WORLD_SPRITES, System, World
from jobs import Job
from races import RACES, attitude
from ships import CLASSES, Outfit, Ship


def quote(value) -> str:
    """One token, quoted only as much as it needs to be."""
    text = str(value)
    if text == "":
        return '""'
    if '"' in text:
        return f"`{text}`"
    if any(c in text for c in " \t'"):
        return f'"{text}"'
    return text


def number(value) -> str:
    """Numbers written the way the engine writes them: no trailing noise."""
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)

    rounded = round(float(value), 6)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:g}"


class Writer:
    def __init__(self):
        self.lines: List[str] = []

    def line(self, depth: int, *tokens) -> None:
        self.lines.append("\t" * depth + " ".join(str(t) for t in tokens))

    def blank(self) -> None:
        self.lines.append("")

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


HEADER = """# Generated by tools/worldgen. Do not edit by hand — regenerate with:
#     python tools/worldgen/worldgen.py
#
# {what}
"""


def _write(path: str, what: str, writer: Writer) -> int:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER.format(what=what))
        handle.write(writer.text())
    return len(writer.lines)


# --- Governments -------------------------------------------------------------

def governments(root: str) -> int:
    w = Writer()
    pairs = [(race, faction) for race in RACES for faction in race.factions]

    for race, faction in pairs:
        w.line(0, "government", quote(faction.name))
        w.line(1, quote("display name"), quote(faction.name))
        w.line(1, quote("crew attack"), number(faction.crew_attack))
        w.line(1, quote("crew defense"), number(faction.crew_defense))

        # A hostile people is hostile to strangers by default; a mercantile one
        # is not. Without this, anyone not named explicitly is a friend.
        default = -0.2 if race.temperament in ("predatory", "expansionist") else 0.0
        w.line(1, quote("default attitude"), number(default))

        # Hostility toward the PLAYER is reputation, not the attitude matrix -
        # upstream scopes the matrix to government-vs-government and asks standing
        # for anything involving the player. Without this every raider in the Reach
        # flies past a defenceless freighter without a second look, and no bounty
        # is ever a fight.
        if faction.role == "fringe":
            w.line(1, quote("player reputation"), number(-1000))
        elif faction.role == "zealot":
            w.line(1, quote("player reputation"), number(-50))
        else:
            w.line(1, quote("player reputation"), number(1))

        w.line(1, quote("attitude toward"))
        for other_race, other in pairs:
            value = attitude(race, faction, other_race, other)
            if value != 0.0:
                w.line(2, quote(other.name), number(value))

        w.blank()

    # Derelicts exist so salvage jobs have something to point at.
    w.line(0, "government", quote("Derelict"))
    w.line(1, quote("display name"), quote("Derelict"))
    w.line(1, quote("default attitude"), number(0))
    w.blank()

    return _write(os.path.join(root, "governments.txt"),
                  f"{len(pairs) + 1} governments across {len(RACES)} peoples", w)


# --- Outfits and ships -------------------------------------------------------

def outfits(root: str, items: List[Outfit]) -> int:
    w = Writer()
    for item in items:
        w.line(0, "outfit", quote(item.name))
        w.line(1, "category", quote(item.category))
        w.line(1, "cost", number(item.cost))
        for key, value in item.attributes.items():
            w.line(1, quote(key), number(value))

        if item.weapon:
            w.line(1, "weapon")
            for key, value in item.weapon.items():
                if isinstance(value, str):
                    w.line(2, quote(key), quote(value))
                else:
                    w.line(2, quote(key), number(value))

        if item.description:
            w.line(1, "description", f"`{item.description}`")

        w.blank()

    return _write(os.path.join(root, "outfits.txt"), f"{len(items)} outfits", w)


def ships(root: str, fleet: List[Ship]) -> int:
    w = Writer()
    for ship in fleet:
        w.line(0, "ship", quote(ship.name))
        w.line(1, "sprite", quote(f"ship/{ship.race.key}/{ship.ship_class.name.lower().replace(' ', '-')}"))
        w.line(1, "attributes")
        w.line(2, "category", quote(ship.ship_class.name))
        for key, value in ship.attributes.items():
            w.line(2, quote(key), number(value))

        if ship.outfits:
            w.line(1, "outfits")
            for name, count in ship.outfits:
                if count > 1:
                    w.line(2, quote(name), number(count))
                else:
                    w.line(2, quote(name))

        for x, y in ship.guns:
            w.line(1, "gun", number(x), number(y))
        for x, y in ship.turrets:
            w.line(1, "turret", number(x), number(y))
        for x, y in ship.engines:
            w.line(1, "engine", number(x), number(y))

        w.line(1, "description", f"`{ship.description}`")
        w.blank()

    return _write(os.path.join(root, "ships.txt"),
                  f"{len(fleet)} ships across {len(CLASSES)} classes", w)


def shops(root: str, fleet: List[Ship], items: List[Outfit]) -> int:
    """A shipyard and an outfitter per race, stocking that race's own work."""
    w = Writer()

    for race in RACES:
        own_ships = [s.name for s in fleet if s.race.key == race.key]
        if own_ships:
            w.line(0, "shipyard", quote(f"{race.key} shipyard"))
            for name in sorted(own_ships):
                w.line(1, quote(name))
            w.blank()

        prefix = race.name.split()[0]
        own_outfits = [o.name for o in items if o.name.startswith(prefix + " ")]
        if own_outfits:
            w.line(0, "outfitter", quote(f"{race.key} outfitter"))
            for name in sorted(own_outfits):
                w.line(1, quote(name))
            w.blank()

    return _write(os.path.join(root, "shops.txt"),
                  f"{len(RACES)} shipyards and outfitters", w)


def fleets(root: str, fleet: List[Ship]) -> int:
    """Fleet definitions, so systems have traffic rather than being empty."""
    w = Writer()
    count = 0

    for race in RACES:
        own = [s for s in fleet if s.race.key == race.key]
        if not own:
            continue

        traders = [s for s in own if s.ship_class.role in ("trader", "civilian")]
        warships = [s for s in own if s.ship_class.role == "warship"]
        utility = [s for s in own if s.ship_class.role in ("utility", "recon")]

        for faction in race.factions:
            if faction.role in ("trade", "corporate"):
                pool, size = traders or own, (1, 3)
            elif faction.role == "fringe":
                pool, size = (warships + utility) or own, (1, 3)
            else:
                pool, size = warships or own, (2, 4)

            w.line(0, "fleet", quote(f"{faction.name} Patrol"))
            w.line(1, "government", quote(faction.name))
            w.line(1, "names", quote(f"{race.key} names"))

            for index, ship in enumerate(pool[:4]):
                w.line(1, "variant", number(30 - index * 6))
                w.line(2, quote(ship.name), number(size[0] + index % size[1]))

            w.blank()
            count += 1

    return _write(os.path.join(root, "fleets.txt"), f"{count} fleets", w)


# --- Systems and worlds ------------------------------------------------------

def _world(w: Writer, world: World, depth: int) -> None:
    w.line(depth, "object", quote(world.name))
    w.line(depth + 1, "sprite", quote(WORLD_SPRITES[world.kind]))
    w.line(depth + 1, "distance", number(world.distance))
    w.line(depth + 1, "period", number(world.period))
    for moon in world.moons:
        _world(w, moon, depth + 1)


def systems(root: str, galaxy: List[System]) -> int:
    w = Writer()

    for system in galaxy:
        w.line(0, "system", quote(system.name))
        w.line(1, "pos", number(system.x), number(system.y))
        if system.government:
            w.line(1, "government", quote(system.government))
        w.line(1, "habitable", number(system.habitable))

        if system.arrival:
            w.line(1, "arrival", number(system.arrival))

        for link in sorted(system.links):
            w.line(1, "link", quote(link))

        for name, count, energy in system.asteroids:
            w.line(1, "asteroids", quote(name), number(count), number(energy))
        for name, count, energy in system.minables:
            w.line(1, "minables", quote(name), number(count), number(energy))

        for commodity, price in system.trade.items():
            w.line(1, "trade", quote(commodity), number(price))

        for fleet_name, period in system.fleets:
            w.line(1, "fleet", quote(fleet_name), number(period))

        # Stars sit at the centre; a pair orbits a shared point.
        for index, star in enumerate(system.star_classes):
            w.line(1, "object")
            w.line(2, "sprite", quote(STAR_SPRITES[star]))
            if len(system.star_classes) > 1:
                w.line(2, "distance", number(60 + index * 40))
                w.line(2, "period", number(12))
            else:
                w.line(2, "distance", number(0))
                w.line(2, "period", number(10))

        for world in system.worlds:
            _world(w, world, 1)

        w.blank()

    return _write(os.path.join(root, "systems.txt"),
                  f"{len(galaxy)} systems", w)


def planets(root: str, galaxy: List[System]) -> int:
    w = Writer()
    count = 0

    def emit(world: World) -> None:
        nonlocal count
        w.line(0, "planet", quote(world.name))
        if world.government:
            w.line(1, "government", quote(world.government))
        if world.attributes:
            w.line(1, "attributes", *[quote(a) for a in world.attributes])
        if world.inhabited:
            w.line(1, "spaceport", f"`{world.spaceport}`")
            w.line(1, "security", number(world.security))
            if world.shipyard:
                w.line(1, "shipyard", quote(world.shipyard))
            if world.outfitter:
                w.line(1, "outfitter", quote(world.outfitter))
        w.blank()
        count += 1

        for moon in world.moons:
            emit(moon)

    for system in galaxy:
        for world in system.worlds:
            emit(world)

    return _write(os.path.join(root, "planets.txt"), f"{count} worlds", w)


# --- Jobs --------------------------------------------------------------------

def _filter(w: Writer, depth: int, spec: Dict[str, object]) -> None:
    for key, value in spec.items():
        if key == "distance":
            low, high = value  # type: ignore[misc]
            w.line(depth, "distance", number(low), number(high))
        elif isinstance(value, (list, tuple)):
            w.line(depth, key, *[quote(v) for v in value])
        else:
            w.line(depth, key, quote(value))


def _stable_hash(text: str) -> int:
    """A hash that is the same in every process.

    Python salts str.__hash__ with PYTHONHASHSEED, which is random per run unless
    it is set, so `hash(name) % len(pool)` picked a different ship for every job on
    every run. That made jobs.txt the one generated file that could not be
    reproduced -- the committed one was written under a salt nobody has -- while the
    module docstring promised everything here is regenerable from the seed. CRC32 is
    stable across processes, platforms and Python versions, and keeps the property
    that actually mattered: the choice is a function of the job's name.
    """
    return zlib.crc32(text.encode("utf-8"))


def missions(root: str, work: List[Job], fleet: List[Ship]) -> int:
    w = Writer()
    by_race: Dict[str, List[Ship]] = {}
    for ship in fleet:
        by_race.setdefault(ship.race.key, []).append(ship)

    for job in work:
        w.line(0, "mission", quote(job.name))
        w.line(1, "name", f"`{job.display}`")
        w.line(1, "description", f"`{job.description}`")
        w.line(1, "job")
        if job.repeat:
            w.line(1, "repeat")

        w.line(1, "source")
        _filter(w, 2, job.source_filter)

        w.line(1, "destination")
        _filter(w, 2, job.destination_filter)

        if job.cargo:
            commodity, tons = job.cargo
            w.line(1, "cargo", quote(commodity), number(tons))
        if job.passengers:
            w.line(1, "passengers", number(job.passengers))
        if job.deadline:
            w.line(1, "deadline", number(job.deadline))

        w.line(1, "to", "offer")
        w.line(2, "has", quote("flagship landed"))

        if job.npc:
            npc = job.npc
            objective = str(npc["objective"])
            w.line(1, "npc", objective, *(["accompany"] if npc.get("accompany") else []))
            w.line(2, "government", quote(str(npc["government"])))
            personality = npc.get("personality") or []
            if personality:
                w.line(2, "personality", *[quote(p) for p in personality])  # type: ignore[union-attr]

            # `system destination` is a keyword, not a system name: it defers
            # placement to wherever the job sends the player. Bounties and salvage
            # both read "near <destination>", so that is where the hulls belong.
            # An escort travels WITH the player, so it starts where they do.
            if npc.get("at_destination"):
                w.line(2, "system", "destination")

            # One `ship` line per hull. The second token of a `ship` line is the
            # individual name, not a count - a number there names one ship "3" and
            # silently places a single hull where three were meant.
            pool = by_race.get(str(npc.get("race")), fleet)
            picked = pool[_stable_hash(job.name) % len(pool)] if pool else None
            if picked is not None:
                for _ in range(max(1, int(npc.get("count", 1)))):
                    w.line(2, "ship", quote(picked.name))

        w.line(1, "on", "complete")
        w.line(2, "payment", number(job.payment))
        w.blank()

    return _write(os.path.join(root, "jobs.txt"), f"{len(work)} jobs", w)


def start(root: str, galaxy: List[System]) -> int:
    """Where a new pilot begins: a quiet, inhabited world with a shipyard."""
    w = Writer()

    candidates = [
        (system, world)
        for system in galaxy
        if system.race is not None and len(system.links) >= 2
        for world in system.worlds
        if world.inhabited and world.shipyard
    ]
    candidates.sort(key=lambda pair: (-len(pair[0].links), pair[0].name))
    system, world = candidates[0]

    w.line(0, "start", quote("reach"))
    w.line(1, "name", quote("The Reach"))
    w.line(1, "description", f"`You begin on {world.name}, in the {system.name} system, "
                             f"under {system.government or 'no flag in particular'}. "
                             f"The Reach is twenty peoples deep and nobody has mapped all of it.`")
    w.line(1, "date", 16, 11, 3013)
    w.line(1, "system", quote(system.name))
    w.line(1, "planet", quote(world.name))
    w.line(1, "account")
    w.line(2, "credits", 480000)
    w.line(1, "set", quote("start: reach"))
    w.line(1, "set", quote("species: human"))
    w.blank()

    _write(os.path.join(root, "start.txt"), "the starting scenario", w)
    return 1


def commodities(root: str) -> int:
    """The trade goods every world quotes a price for."""
    from galaxy import COMMODITY_BASE

    w = Writer()
    w.line(0, "trade")
    for name, base in COMMODITY_BASE.items():
        w.line(1, "commodity", quote(name), number(int(base * 0.45)), number(int(base * 1.9)))
        for word in ("bulk", "crated", "sealed", "loose", "palletised"):
            w.line(2, quote(f"{word} {name.lower()}"))
    w.blank()

    return _write(os.path.join(root, "commodities.txt"),
                  f"{len(COMMODITY_BASE)} trade goods", w)


def minables(root: str) -> int:
    from galaxy import MINABLES

    w = Writer()
    values = {"iron": 90, "copper": 140, "silver": 320, "gold": 620,
              "titanium": 410, "uranium": 880, "silicon": 180,
              "platinum": 1150, "iridium": 1420, "neodymium": 760}

    for ore in MINABLES:
        w.line(0, "minable", quote(ore))
        w.line(1, "sprite", quote(f"asteroid/{ore}/spin"))
        w.line(1, "hull", number(600 + values[ore]))
        w.line(1, quote("random hull"), number(200))
        w.line(1, "payload", quote(ore.capitalize()), number(30))
        w.blank()

        # The ore itself, so a payload has something to be.
        w.line(0, "outfit", quote(ore.capitalize()))
        w.line(1, "category", quote("Minerals"))
        w.line(1, "cost", number(values[ore]))
        w.line(1, quote("mass"), number(1))
        w.line(1, "description", f"`Raw {ore}, as it comes out of a rock.`")
        w.blank()

    return _write(os.path.join(root, "minables.txt"), f"{len(MINABLES)} mineable ores", w)
